### ISSUE TITLE
Move build system to it's own repo?

### ISSUE THREAD

**Issue by LeonardMeagher2** [SurLaTable/slt-ui#63]
@ryanpcmcquen had the idea to separate our components and the build system that makes it possible to use them on the legacy site. I don't know how much complexity that'd add, but we can talk about ideas here.

slt-ui could become a fork of the build system repo, with our own components inside.

**Comment by ryanpcmcquen** [comment]
I was thinking slt-ui could just require the build system? Or the build system could require/import components from another repo. Also, we need to rename everything anyways. So it could look something like:

```
@georgetown-labs/components
@georgetown-labs/SOMETHING
```

Not sure what to call the build system part. Maybe `core`, or `hub`, or `integrator`. I'm open to suggestions because I can't think of any good things right now.

**Comment by ryanpcmcquen** [comment]
I like the name `@georgetown-labs/framework`, for the non-component portion.
